@ECHO off
ECHO Creating java source code files list...
DIR /B /S *.java > sources.txt
ECHO Compiling all source files...
javac -d bin -cp src;lib\hamcrest-core-1.3.jar;lib\junit-4.13-beta-3.jar;lib\JUnitParams.jar -encoding UTF-8 @sources.txt
ECHO Finished
